export const imagePrompts = [
  "A serene mountain lake at sunrise.",
  "An ancient castle under a starry night.",
  "A futuristic cityscape with flying cars.",
  "A bustling marketplace in Marrakech.",
  "An underwater scene with colorful coral reefs.",
  "A lush tropical rainforest with exotic birds.",
  "A tranquil beach at sunset with palm trees.",
  "A medieval knight in full armor.",
  "A majestic eagle soaring in the sky.",
  "A vibrant street art mural.",
  "A serene Japanese garden with a koi pond.",
  "A bustling New York City street.",
  "A quaint European village in autumn.",
  "A herd of wild horses in a meadow.",
  "A mystical dragon in a cave.",
  "A futuristic space station orbiting a planet.",
  "A cozy cabin in a snowy forest.",
  "A bustling Chinatown market.",
  "A coral reef teeming with marine life.",
  "A magnificent waterfall in the Amazon.",
  "A vibrant Indian Holi festival.",
  "A retro diner with a jukebox.",
  "A tranquil lakeside campfire.",
  "A Viking ship at sea.",
  "A bustling Moroccan bazaar.",
  "A field of colorful hot air balloons.",
  "A serene bamboo forest in Japan.",
  "A futuristic city on another planet.",
  "A medieval fantasy village.",
  "A regal peacock displaying its feathers.",
  "A futuristic cyberpunk street.",
  "A tranquil cottage by a river.",
  "A Native American powwow.",
  "A coral reef with hidden treasures.",
  "A serene cherry blossom garden.",
  "A bustling carnival at night.",
  "A medieval fantasy dragon.",
  "A futuristic cityscape with neon lights.",
  "A cozy winter cabin by a frozen lake.",
  "A bustling Indian street market.",
  "A herd of African elephants on the savannah.",
  "A mystical unicorn in a forest.",
  "A serene field of lavender in Provence, France.",
  "A bustling Tokyo street at Shibuya Crossing.",
  "An ancient Egyptian pyramid against a desert backdrop.",
  "A surreal underwater city with mermaids and marine life.",
  "A tranquil English countryside with rolling hills.",
  "A futuristic spaceport on a distant alien planet.",
  "A cozy log cabin in a snowy forest with a warm fire inside.",
  "A lively Brazilian carnival with colorful costumes and samba dancers.",
  "A medieval wizard casting a spell in a mystical forest.",
  "A majestic lion in the African savannah.",
  "A vibrant street food market in Bangkok, Thailand.",
  "A serene pagoda in a misty Japanese garden.",
  "An old-timey Wild West town with cowboys and saloons.",
  "A coral reef with hidden shipwrecks and treasure chests.",
  "A tranquil cherry blossom grove in springtime.",
  "A bustling Parisian cafe with people enjoying coffee and pastries.",
  "A futuristic city on Mars with advanced technology.",
  "A cozy cottage in the Swiss Alps surrounded by snow-capped mountains.",
  "A lively Mexican Dia de los Muertos celebration with sugar skulls.",
  "A medieval castle on a cliff overlooking the sea.",
  "A majestic polar bear in the Arctic wilderness.",
  "A bustling food market in Marrakech, Morocco.",
  "A mystical forest with fairies and magical creatures.",
  "A futuristic cyberpunk city with neon signs and flying cars.",
  "A tranquil lakeside cabin with a rowboat on the shore.",
  "A Native American powwow with traditional dances and regalia.",
  "A serene cherry blossom garden in the moonlight.",
  "A bustling Italian piazza with cafes and musicians.",
  "A medieval battle with knights and siege engines.",
  "A futuristic cityscape with holographic billboards and AI assistants.",
  "A breathtaking view of the Earth from the International Space Station.",
  "The majestic rings of Saturn up close.",
  "A spacewalk on the surface of the Moon.",
  "A panoramic view of the Martian landscape from a rover.",
  "The fiery atmosphere of the Sun with solar flares.",
  "A close encounter with Jupiter's Great Red Spot.",
  "A serene view of the Earth's moon against the night sky.",
  "The icy beauty of Pluto and its moon, Charon.",
  "An asteroid belt teeming with rocky bodies.",
  "A futuristic colony on Mars with domed habitats.",
  "A comet streaking through the night sky.",
  "The stunning auroras on Uranus.",
  "The rugged terrain of Mercury.",
  "A space probe exploring the outer reaches of the solar system.",
  "A cosmic dance of the planets in alignment.",
  "The interior of a spacecraft on a mission to Mars.",
  "The mysterious dark side of the Moon.",
  "A meteor shower lighting up the Earth's atmosphere.",
  "A colony on a distant moon of Jupiter.",
  "A telescope observing distant galaxies.",
  "An astronaut's helmet reflecting the beauty of space.",
  "A Martian colony with greenhouses and gardens.",
  "The birth of a star in a stellar nursery.",
  "An eclipse with the Moon passing in front of the Sun.",
  "A close-up of a comet's nucleus.",
  "A space elevator connecting Earth to space.",
  "A spaceport on a distant exoplanet.",
  "The vast Oort Cloud on the edge of the solar system.",
  "A Martian base with futuristic transportation.",
];

export function getRandomImagePrompt() {
  const randomIndex = Math.floor(Math.random() * imagePrompts.length);
  return imagePrompts[randomIndex];
}
